version: "3.8"
services:
  api:
    build:
      context: .
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"
    command:
      sh -c "python test_starship.py && flake8 &&
      gunicorn wsgi:application -b 0.0.0.0:5000"


